
@baseUrl = http://localhost:3000

###  AppControllerGetHello

# @name AppControllerGetHello

GET {{baseUrl}}/home/hello

# RECADOS
### LISTA TODOS OS RECADOS
GET {{baseUrl}}/recados
?limit=200
&offset=300
### LISTA APENAS UM RECADO
GET {{baseUrl}}/recados/2
### CRIA UM NOVO RECADO
POST {{baseUrl}}/recados
Content-Type: application/json

  {
    "texto": "Novo recado",
    "de": "Joana",
    "para": "João"
  }

### ATUALIZA UM RECADO
PATCH {{baseUrl}}/recados/5
Content-Type: application/json

  {
    "texto": "Este é um recado de teste 1",
    "lido": true
  }

### DELETA UM RECADO
DELETE {{baseUrl}}/recados/2




/// 



# PESSOAS
### LISTA TODOS OS PESSOAS
GET {{baseUrl}}/pessoas
?limit=200
&offset=300
### LISTA APENAS UM PESSOA
GET {{baseUrl}}/pessoas/2
### CRIA UM NOVO PESSOA
POST {{baseUrl}}/pessoas
Content-Type: application/json

  {
    "nome": "João",
    "email": "joao@email.com",
    "password": "123456"
  }

### ATUALIZA UM PESSOA
PATCH {{baseUrl}}/pessoas/5
Content-Type: application/json

  {
    "texto": "Este é um recado de teste 1",
    "lido": true
  }

### DELETA UM PESSOA
DELETE {{baseUrl}}/pessoas/2
