
@baseUrl = http://localhost:3000

###  AppControllerGetHello

# @name AppControllerGetHello

GET {{baseUrl}}/home/hello

# RECADOS
### LISTA TODOS OS RECADOS
GET {{baseUrl}}/recados
?limit=200
&offset=300
### LISTA APENAS UM RECADO
GET {{baseUrl}}/recados/2
### CRIA UM NOVO RECADO
POST {{baseUrl}}/recados
Content-Type: application/json

  {
    "texto": "Novo recado",
    "de": "Joana",
    "para": "João"
  }

### ATUALIZA UM RECADO
PATCH {{baseUrl}}/recados/2
Content-Type: application/json

  {
    "texto": "Este é um recado de teste"
  }

### DELETA UM RECADO
DELETE {{baseUrl}}/recados/2

